### ISSUE TITLE
在FancyWindow中添加QDockWidget后，不能拉伸QDockWidget

### ISSUE THREAD

**Issue by wangdemon** [canpool/qtcanpool#3]
在QMainWindow窗口，如果添加QDockWidget窗口，是可以拉伸QDockWidget

在FancyWindow窗口中，添加QDockWidget后，不能拉伸QDockWidget

看下面演示视频

使用FancyWindow，QDockWindow无法拉伸视频

https://user-images.githubusercontent.com/20681339/233599709-b8f1457a-c37b-48ce-96db-92416e84c832.mp4

使用QMainWindow，QDockWindow可以拉伸视频

https://user-images.githubusercontent.com/20681339/233599802-51474982-334e-4e88-8c03-00d1ecc1c110.mp4

**Comment by canpool** [comment]
非常感谢你的反馈！

**Comment by canpool** [comment]
问题的大概原因是FancyTitleBar作为FancyWindow的事件过滤器，在处理关键鼠标事件时，默认都返回true，即不继续传递事件。导致鼠标动作失效。
目前提交 https://github.com/canpool/qtcanpool/commit/7b83c2ddfe25f7a2f087d311f85c465ab8cadb5b 经过初步测试，可以解决该问题。

**Comment by wangdemon** [comment]
感谢老哥，修复这么快
