### ISSUE TITLE
demo mainwindow在linux下，最大化会崩溃？

### ISSUE THREAD

**Issue by Washington-DC** [canpool/qtcanpool#4]
demo mainwindow在linux下，最大化会崩溃？ 银河麒麟系统，QT5.15.2

**Comment by canpool** [comment]
请问，具体是哪个demo，如果方便，可以把问题图片放上来。是 qxwindow 中的 mainwindow？
![image](https://github.com/user-attachments/assets/fe9e0b39-d0a3-406a-850e-c640f02c3d7f)

**Comment by Washington-DC** [comment]
> 请问，具体是哪个demo，如果方便，可以把问题图片放上来。是 qxwindow 中的 mainwindow？ ![image](https://private-user-images.githubusercontent.com/22664175/380503705-fe9e0b39-d0a3-406a-850e-c640f02c3d7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNzQ4NzIsIm5iZiI6MTczMDA3NDU3MiwicGF0aCI6Ii8yMjY2NDE3NS8zODA1MDM3MDUtZmU5ZTBiMzktZDBhMy00MDZhLTg1MGUtYzY0MGYwMmMzZDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAwMTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMDczZGQ4OTIzMTM3MzFmMzdlM2IyNjI3ZGRjMDZmMTI1OWRhZmVkMWE2MjY2OThkOGFiNmQyNmVmMDc4NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Iu2Hlh0A5k_aJave6AvrfpnYqwoMj_vToK0LBkM8ZQ8)

是的

**Comment by canpool** [comment]
在openEuler GNOME桌面上没有问题，是银河麒麟V10么？放弃吧，不打算在linux上浪费时间，麒麟有自己的ukui，尽量不要定制化吧。

**Comment by canpool** [comment]
我下了一个银河麒麟V10 SP1没安装起来，下载 OpenKylin 2.0 安装后，是qt6，且对deb包不熟悉。后来在 openEuler ukui （镜像地址：https://archives.openeuler.openatom.cn/openEuler-22.09/workstation/x86_64/ ）上测试，没出现最大化崩溃问题。不过，还是建议linux上最好还是别定制标题栏了，效果不好。
![image](https://github.com/user-attachments/assets/f82e972f-5983-4c3d-a3c5-3ada5631a5b4)
